### PR TITLE
Uses xz instead of gz compression format

### PR DESCRIPTION
**Pull request by samueloph**
The use of xz should improve a lot the exported file regarding to its filesize, a simple test resulted in a gain greater than 100%..

### CODE REVIEW

**Comment by ctgraham** [comment]
I have similar concerns as expressed here:
https://github.com/pkp/pkp-lib/pull/747#issuecomment-140841740

**Comment by samueloph** [comment]
Hi @ctgraham,

I don't understand why the the concerns of #747 apply here.

The xz generated, at least in this case (as oposed to #747), is going to be treated by this same plugin.

Since changing from bz to xz should have no impact other than the filesize improvement
 on the user end.

**Comment by ctgraham** [comment]
I might be misreading this, but if I've used full journal export to this point on a system prior to this patch, I won't be able to use that output file as input for another system with this patch applied.

**Comment by samueloph** [comment]
Oh, you're right, Sorry @ctgraham.

I was thinking that this plugin was on early stage development and just a few people tested here in Brazil, but it can be that there's already people relying on it.

**Comment by samueloph** [comment]
Closing this PR in favour of a backwards compatible one.

Thanks @ctgraham!

**Pull request closed without merging**
